name: hirc
version: 0.0.3

library:
  source-dirs: src
  dependencies:
    - base
    - mtl >= 2.3.1
    - transformers
    - containers
    - array
    - directory
    - stm
    - safecopy
    - acid-state
    - irc
    - network
    - connection
    - text
    - bytestring
    - time
    - regex-posix
    - monad-peel
    - random
    - MonadRandom >= 0.6
    - random-shuffle
    - extra
    - aeson

executables:
  app:
    source-dirs: app
    main: Main.hs
    other-modules:
      Hirc.Modules
      Hirc.Modules.Admin
      Hirc.Modules.Admin.Acid
    dependencies:
      - hirc
      - base
      - mtl >= 2.3
      - containers
      - acid-state
      - bytestring
      - stm
      - time
      - monad-peel

tests:
  spec:
    main: "Spec.hs"
    ghc-options: "-threaded -O0"
    source-dirs:
      - test
    dependencies:
      - hirc
      - base
      - hspec
      - hspec-expectations
      - random
      - containers